#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  couchdb10:
    container_name: couchdb10
    image: hyperledger/fabric-couchdb:latest
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "14984:5984"

  peer0.org10.example.com:
    container_name: peer0.org10.example.com
    extends:
      file:  base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org10.example.com
      - CORE_PEER_LOCALMSPID=Org10MSP
      - CORE_PEER_ADDRESS=peer0.org10.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb10:5984
    ports:
      - 16051:7051
      - 16053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org10.example.com/peers/peer0.org10.example.com/:/etc/hyperledger/crypto/peer
        - ../mount/peer0.org10.example.com/var/hyperledger/production:/var/hyperledger/production
    depends_on:
        - couchdb10
